### ISSUE TITLE
Z Fighting and visible cube on gel converter

### ISSUE THREAD

**Issue by Areng14** [CardsAndGamesYT/The-Cards-And-Games-Pack#2]
As you can tell by the title you can see Z fighting and a visible cube on the entrance side of the gel converter I am using the experimental and just wanted you to know
![image](https://user-images.githubusercontent.com/97821562/157628410-e8816844-90a5-4456-8758-74cc386ea04d.png)

**Comment by CardsAndGamesYT** [comment]
Thank you for letting me know! i will see what i can do. also are you able to jump in? because if so then thats an issue

**Comment by Areng14** [comment]
Yup you are also able to jump through also the cube has zero gravity so if you touch it it will just float through walls and stuff

**Comment by CardsAndGamesYT** [comment]
Thanks for letting me know, ill take a look and fix it!

**Comment by Areng14** [comment]
Also you should make it like cube type thing
That would be better

**Comment by CardsAndGamesYT** [comment]
i am, thats gonna be part of the 1.5.0 update
