### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by Areng14** [CardsAndGamesYT/The-Cards-And-Games-Pack#4]
In the incinerator item it says Specail instead of Special.
![image](https://user-images.githubusercontent.com/97821562/168428979-d8e27087-ee8b-4789-b090-1e97651533c9.png)

**Comment by CardsAndGamesYT** [comment]
LMAO, ill fix this soon lol

**Comment by Areng14** [comment]
that took so long lol

**Comment by CardsAndGamesYT** [comment]
yea 9 months = soon
